### ISSUE TITLE
I have issues

### ISSUE THREAD

**Issue by brycebaril** [thlorenz/active-handles#1]

**Comment by thlorenz** [comment]
Will investigate. They are definitely there

```
NODE_DEBUG=nsolid NSOLID_HUB=localhost:4001 node -e 'require("http").createServer(function (req, res) {res.end("ok\n")}).listen(8000); console.log(process._getActiveHandles());'
```

Outputs one connection handle. So either active-handles is ignoring it for some reason or the agent doesn't transmit it.

It may also have to do with the fact that you registered no listener in userland, i.e. the below executed inside active-handles works:

```
require("http")
  .createServer(function (req, res) { res.end("ok\n")})
  .listen(8000, onlistening);
  
function onlistening() { }

console.log(require('../').print());
```
